# source for keybindings moved to dms/keybindings
# so I have them ready in case I switch to something else

$menu = vicinae toggle
bind = $mainMod, SUPER_L, exec, $menu
bind = $mainMod, V, exec, vicinae vicinae://extensions/vicinae/clipboard/history
bind = $mainMod, PERIOD, exec, vicinae vicinae://extensions/vicinae/core/search-emojis

bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

bind = , Print, exec, grimblast --freeze copysave area
bind = $mainMod, Print, exec, grimblast --freeze copysave active
bind = CONTROL, Print, exec, grimblast --freeze copysave output
bind = CONTROL SHIFT, Print, exec, grimblast --freeze copysave screen
