# GENERATED BY GEMINI
# doesn't work 🙄
# https://gemini.google.com/app/3e13414000bc8f9a

{ config, pkgs, ... }:

let
  headset-switcher = pkgs.writers.writePython3Bin "headset-switcher" {
    libraries = [ ];
  } ''
    import subprocess
    import glob
    import time


    # Configuration
    VENDOR_ID = "413c"
    OFF_SIG = b'\x08\xc0\x09\x03\x00\x01\xdd\x1e'
    ON_SIG = b'\x08\xc0\x09\x03\x00\x01\xcc\x0f'

    SINK_HEADSET = (
        "alsa_output.usb-Dell_Inc_AWPRO_H_Wireless_Game_"
        "0000000000000000-00.analog-stereo"
    )
    SINK_HDMI = "alsa_output.pci-0000_01_00.1.hdmi-stereo"


    def notify(title, message, icon="audio-headphones"):
        cmd = [
            "notify-send", "-a", "Audio Switcher",
            "-i", icon, title, message
        ]
        try:
            subprocess.run(cmd, check=False)
        except Exception:
            pass


    def set_sink(name, label):
        print(f"DEBUG: Attempting to switch to {label}")
        result = subprocess.run(
            ["wpctl", "set-default", name],
            capture_output=True
        )
        if result.returncode == 0:
            notify("Audio Output Changed", f"Active: {label}")
        else:
            print(f"ERROR: wpctl could not find {name}")


    def find_hid_node():
        # Look specifically for the node that supports Report ID 8
        # Based on your hid-recorder output, we know it's a Dell device
        paths = glob.glob("/sys/class/hidraw/hidraw*/device/uevent")

        # We check them in reverse because the 'special' nodes
        # like hidraw7 are often created last.
        for path in reversed(sorted(paths)):
            try:
                with open(path, 'r') as f:
                    content = f.read()
                    if "PRODUCT=" in content and VENDOR_ID in content.lower():
                        node = "/dev/" + path.split('/')[4]
                        return node
            except Exception:
                continue
        return None


    def main():
        while True:
            node = find_hid_node()
            if node:
                # This print will show up in journalctl
                print(f"INFO: Monitoring {node} for Alienware Pro signals...")
                try:
                    with open(node, 'rb') as f:
                        while True:
                            # Read one byte at a time to find the start of a signal
                            # This handles alignment issues better than f.read(8)
                            chunk = f.read(8)
                            if not chunk:
                                break

                            if ON_SIG in chunk:
                                set_sink(SINK_HEADSET, "Alienware Headset")
                            elif OFF_SIG in chunk:
                                set_sink(SINK_HDMI, "HDMI Audio")
                except (PermissionError, FileNotFoundError) as e:
                    print(f"ERROR: {e}. Retrying in 5s...")
            time.sleep(5)


    if __name__ == "__main__":
        main()
  '';
in
{
  services.udev.extraRules = ''
    KERNEL=="hidraw*", ATTRS{idVendor}=="413c", MODE="0666"
  '';

  systemd.user.services.alienware-switcher = {
    description = "Alienware Headset Audio Switcher";
    wantedBy = [ "graphical-session.target" ];
    partOf = [ "graphical-session.target" ];
    path = [ pkgs.libnotify pkgs.wireplumber ];
    serviceConfig = {
      ExecStart = "${headset-switcher}/bin/headset-switcher";
      Restart = "always";
      RestartSec = 3;
    };
  };
}
