##############################
### WINDOWS AND WORKSPACES ###
##############################
$mod = $mainMod

# Application Launchers
bind = $mainMod, SUPER_L, exec, dms ipc call spotlight toggle
bind = $mainMod, space, exec, dms ipc call spotlight toggle
bind = $mainMod, V, exec, dms ipc call clipboard toggle
bind = $mainMod, P, exec, dms ipc call processlist focusOrToggle
bind = $mainMod, P, exec, dms ipc call processlist focusOrToggle
bind = $mainMod, comma, exec, dms ipc call settings focusOrToggle
bind = $mainMod, N, exec, dms ipc call widget toggle notificationButton
bind = $mainMod, Y, exec, dms ipc call dankdash wallpaper
bind = $mainMod, TAB, exec, dms ipc call hypr toggleOverview
bind = $mainMod, W, exec, dms ipc call widget toggle weather

# Security
bind = $mainMod ALT, L, exec, dms ipc call lock lock

# Audio Controls
bindel = , XF86AudioRaiseVolume, exec, dms ipc call audio increment 3
bindel = , XF86AudioLowerVolume, exec, dms ipc call audio decrement 3
bindl = , XF86AudioMute, exec, dms ipc call audio mute

# Brightness Controls
bindel = , XF86MonBrightnessUp, exec, dms ipc call brightness increment 5
bindel = , XF86MonBrightnessDown, exec, dms ipc call brightness decrement 5

bind = , Print, exec, dms screenshot
bind = $mainMod, Print, exec, dms screenshot window
bind = CONTROL, Print, exec, dms screenshot full
bind = CONTROL SHIFT, Print, exec, dms screenshot all
