# Opacity for inactive windows
# windowrule {
#   name = windowrule-1
#   opacity = 0.9 0.9
#   match:float = 0
#   match:focus = 0
# }


# GNOME apps
windowrule {
  name = windowrule-2
  rounding = 12
  border_size = 0
  match:class = ^(org\.gnome\.)
}


# Terminal apps - no borders
windowrule {
  name = windowrule-3
  border_size = 0
  match:class = ^(org\.wezfurlong\.wezterm)$
}

windowrule {
  name = windowrule-4
  border_size = 0
  match:class = ^(Alacritty)$
}

windowrule {
  name = windowrule-5
  border_size = 0
  match:class = ^(zen)$
}

windowrule {
  name = windowrule-6
  border_size = 0
  match:class = ^(com\.mitchellh\.ghostty)$
}

windowrule {
  name = windowrule-7
  border_size = 0
  match:class = ^(kitty)$
}


# Floating windows
windowrule {
  name = windowrule-8
  float = on
  match:class = ^(gnome-calculator)$
}

windowrule {
  name = windowrule-9
  float = on
  match:class = ^(blueman-manager)$
}

windowrule {
  name = windowrule-10
  float = on
  match:class = ^(org\.gnome\.Nautilus)$
}


# Open DMS windows as floating by default
windowrule {
  name = windowrule-11
  float = on
  match:class = ^(org.quickshell)$
}
