-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "eDP-1", mode = "2560x1600@165.000", position = "0x1440", scale = 2, vrr = 0, bitdepth = 10, sdrsaturation = 1.5 })
hl.monitor({ output = "HDMI-A-2", mode = "3840x2160@60.000", position = "427x0", scale = 1.5, vrr = 0, bitdepth = 10, sdrsaturation = 1.5 })
hl.monitor({ output = "DP-2", mode = "3840x2160@30.000", position = "2987x0", scale = 1.5, transform = 1, vrr = 0 })
