-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "eDP-1", mode = "2560x1600@165.000", position = "0x1440", scale = 1.6015625, vrr = 2, bitdepth = 10, sdrsaturation = 1.5 })
hl.monitor({ output = "DP-2", mode = "3840x2160@30.000", position = "2560x0", scale = 2, transform = 1, vrr = 0 })
hl.monitor({ output = "HDMI-A-2", mode = "3840x2160@120.000", position = "0x0", scale = 1.5, vrr = 2, bitdepth = 10, sdrsaturation = 1.5 })
